### ISSUE TITLE
Updater GitHub action has been failing since June 14 2022

### ISSUE THREAD

**Issue by thekbb** [Netflix-Skunkworks/policyuniverse#164]
It's not clear to me from the GitHub action output what the error is

This makes policy universe less useful as newer actions aren't available.

```
Run cd updater
  cd updater
  python updater.py > output_summary.txt
  output_summary=`cat output_summary.txt`
  output_summary="${output_summary//'%'/'%[2](https://github.com/Netflix-Skunkworks/policyuniverse/actions/runs/3882392654/jobs/6622490960#step:8:2)5'}"
  output_summary="${output_summary//$'\n'/'%0A'}"
  output_summary="${output_summary//$'\r'/'%0D'}"
  echo "::set-output name=updatersummary::$output_summary"
  rm output_summary.txt
  mv output_formatted.json ../policyuniverse/data.json
  cd ..
  sed -ri "s/(version=\"[0-9]+.[0-9]+.[0-9]+.)([0-9]+)\"/\1`date +"%Y%m%d"`\"/g" setup.py
  rm -rf phantomjs-2.1.1-linux-x86_64/
  rm phantomjs-2.1.1-linux-x86_64.tar.bz2
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/Netflix-Skunkworks/policyuniverse/actions/runs/3882392654/jobs/6622490960#step:8:3).8.15/x6[4](https://github.com/Netflix-Skunkworks/policyuniverse/actions/runs/3882392654/jobs/6622490960#step:8:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.1[5](https://github.com/Netflix-Skunkworks/policyuniverse/actions/runs/3882392654/jobs/6622490960#step:8:5)/x[6](https://github.com/Netflix-Skunkworks/policyuniverse/actions/runs/3882392654/jobs/6622490960#step:8:6)4/lib
    AWS_DEFAULT_REGION: us-west-2
    AWS_REGION: us-west-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_ACCOUNT_ID: ***
    AWS_ROLE_NAME: ***
Traceback (most recent call last):
  File "updater.py", line 23[8](https://github.com/Netflix-Skunkworks/policyuniverse/actions/runs/3882392654/jobs/6622490960#step:8:8), in <module>
    main()
  File "updater.py", line 221, in main
    service_data = gather_data_from_console()
  File "updater.py", line 12[9](https://github.com/Netflix-Skunkworks/policyuniverse/actions/runs/3882392654/jobs/6622490960#step:8:9), in gather_data_from_console
    raise Exception(
Exception: Phantom returned non-zero exit code: 1
Error: Process completed with exit code 1.
```

**Comment by rudrakhshap-fens** [comment]
I am getting the same error running this project. I have tried running it both in windows as well as linux. Not sure what the actual error is though

**Comment by thekbb** [comment]
> I am getting the same error running this project. I have tried running it both in windows as well as linux. Not sure what the actual error is though. @thekbb are you able to find any solution/workarounds?

I haven't tried to rub the updater scripts that the GitHub action runs.

**Comment by patricksanders** [comment]
This is now fixed. Sorry for the trouble!
